### ISSUE TITLE
일정 추정

### ISSUE THREAD

**Issue by cca-company** [NHNNEXT/2016-01-HUDIWEB-SAEDAL#2]
* Backlog 할당
* issue에 feature 할당하기

**Comment by fairesy** [comment]
플래닝 포커 사용한 [일정추정](https://github.com/NHNNEXT/2016-01-HUDIWEB-SAEDAL/wiki/2016.3.14-%3A-%EC%9D%BC%EC%A0%95%EC%B6%94%EC%A0%95)
