### ISSUE TITLE
Spring Boot 개발 환경 설정하기

### ISSUE THREAD

**Issue by fairesy** [NHNNEXT/2016-01-HUDIWEB-SAEDAL#43]
- [x] `Spring Initializr` 사용하여 Spring Boot 프로젝트 구조 생성
- [x] 데이터베이스 모델링에 따라 모델 생성
- [x] 데이터베이스 모델링에 따라 DAO 테스트 (CRUD) 개발
- [x] 데이터베이스 모델링에 따라 DAO 개발
- [x] 실제 데이터베이스와 DAO 연동 (CRUD) 테스트

**Comment by Byeol** [comment]
commit 70c09822cf0ca8be6377adab2c0404dad2a2f4be a460747e13f30f3b8e6557b57303d1be21de9457 closed this issue
